# ~/.local/shai/config.yaml

#默认设置
default_model: "glm-4.7-flash"  # 指向 models 中的别名或 ID

#提供商配置
providers:
  deepseek:
    api_key: "${DEEPSEEK_API_KEY}"  # 建议支持从环境变量读取，如 ${DEEPSEEK_API_KEY}
    base_url: "https://api.deepseek.com"
  智普:
    api_key: "sk-..." # 建议支持从环境变量读取，如 ${GLM_API_KEY}
    base_url: "https://open.bigmodel.cn/api/paas/v4"


#模型定义
models:
  - id: "deepseek-chat"
    provider: "deepseek"
  - id: "glm-4.7-flash"
    provider: "智普"
